export const reactVersion: string;
export const reactVendorFile: string;
export function buildReactVendor(options?: { force?: boolean }): string;
export const typescriptVersion: string;
export const typescriptVendorDir: string;
export function buildTypeScriptVendor(options?: { force?: boolean }): string;
export const reactTypesVendorDir: string;
export function buildReactTypesVendor(options?: { force?: boolean }): string;
export const pgliteVendorDir: string;
export function buildPgliteVendor(options?: { force?: boolean }): string;
